### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SergeRPM** [zelcash/zelflux#131]
Hi! 
I have the problem with the ip address. 
In details zelbench-cli getbenchmarks returns an unknowing ip address wich is different from the address in the configuration /.zelcash/zelcash.conf. This is not mein external ip. 
This is the reason of mistakes in the flux and in the zelbench:
error.log: 	My Flux unavailability detected from XXX.XXX.XXX.XXX
		Flux is not available for outside communication
		...
./zelbenchmark/debug.log
2020-07-26 20:51:35 Benchmark version v1.0.0-beta1-b16e73c-dirty (2020-07-16 22:58:47 +0200)
2020-07-26 20:51:35 Using OpenSSL version OpenSSL 1.1.1a  20 Nov 2018
2020-07-26 20:51:35 HTTP: creating work queue of depth 16
2020-07-26 20:51:35 HTTP: starting 4 worker threads
2020-07-26 20:51:35 Bound to [::]:16225
2020-07-26 20:51:35 Bound to 0.0.0.0:16225
2020-07-26 20:51:35 init message: Done loading
2020-07-26 20:51:35 Starting Zelnodes Benchmarking Thread
2020-07-26 20:51:36 Path: /home/sd/zelflux/ZelBack
2020-07-26 20:52:39 ---ZelFlux did not respond properly. Marked as Failed.
2020-07-26 20:56:39 ---BenchMark failed. Restarting benchmark. Retry number: 1
2020-07-26 20:56:44 ---Restarting benchmarks
2020-07-26 20:56:45 Path: /home/sd/zelflux/ZelBack
2020-07-26 20:57:48 ---ZelFlux did not respond properly. Marked as Failed.
2020-07-26 21:01:23 ---Restarting benchmarks

Could you explain where this address from and how to fix it.

**Enviroment(please complete the following information):**
 - OS: [e.g. Ubuntu 18.04 LTS]
 - Version [e.g. v0.66.0]
 - ZelCash [e.g. v4.0.2]

Best regards

**Comment by TheTrunk** [comment]
Hi @SergeRPM  
Your node is not accessible from outside on the ports needed. Please ensure that ports 16126, 16127, 16128 are fully open. So other peers can connect to your node.

**Comment by SergeRPM** [comment]
Hi! Thanks for the answer.

My external ip address XXX.XXX.69.100.
All necessary ports are open and available from outside.
The Node had worked properly, but had stoped and i supose it happened after the zelflux's upgrading. The command  zelbench-cli getbenchmarks returns not my ip address. Probably it is the reason.

sd@zel01-node:~$ zelbench-cli getbenchmarks
{
  "ipaddress": "XXX.XXX.75.2",
  "status": "failed",
  "time": 1595825507,
  "cores": 0,
  "ram": 0,
  "ssd": 0,
  "hdd": 0,
  "ddwrite": 0,
  "eps": 0
}

Could you expain where the different ip-address from? Why it is not my?

Best regards

**Comment by TheTrunk** [comment]
Hi,
ZelBench has it's own mechanism for detecting true IP on which your node is actually accessible. The reported address from ZelBench is the accurate one and that address is used for all zel/flux purposes. 
That said, Zel and flux does not really care what externalip is set in zelcash.conf file.

**Comment by SergeRPM** [comment]
ok, but i know my ip-address and it is available from outside, all ports are open, the daemon listens them.  
"own mechanism for detecting true IP" detect wrong ip, where the zelcash daemon is not available. 
What shall i do in this case?

**Comment by TheTrunk** [comment]
When you log into your vps and write following command what IP address do you get?
```
curl ipecho.net/plain
```

**Comment by christophsville** [comment]
So did you fiond a solution? Does it have to do with port forwarding?

**Comment by SergeRPM** [comment]
It was an ISP routing problem.

**Comment by Flouis64** [comment]
Hello, I have the same problem. The IP adress indicated in the benchmark is not the IP adress of my computer. @SergeRPM can you explained in details how you have resolved this issue. Thank you for your help

**Comment by AramCoin** [comment]
> It was an ISP routing problem.

I think I have the same issue, how did you manage this ISP routing problem?
